
//discount of 1 means no discount

export const menuItems = [
    {
        name: 'Beyond Burger',
        category: 'burgers',
        price: 8.59,
        discount: 0.8,
        rating: 4.4,
        delivery: '15-20 min',
        img: 'meat-burger.jpg',
        veg: true,
        ingredients: ["Wheat Bun", "Mayo", "Ketchup", "Lettuce", "Tomato", "Onions", "Pickles", "Pea Patty"],
        description: "Beyond Burger is the perfect alternative for those who love delicious, juicy burgers but don't want to miss out on the taste and texture of real beef. Made from peas, this patty is super tasty and juicy, and doesn't contain any cholesterol.",
        id: 1
    },
    {
        name: 'Special 24K Burger',
        category: 'burgers',
        price: 120,
        discount: 1,
        rating: 4.9,
        delivery: '30-45 min',
        img: 'gold-burger.jpg',
        veg: false,
        ingredients: ["Secret Sauce", "Wagyu Beef Patty", "Melted Cheese", "Caramelized Onions", "Tomatoes", "Greens"],
        description: "Our Luxurious Wagyu Beef patty burger is coated in 24 carat gold leaves, giving it a luxurious look and taste. Our secret sauce gives it that extra taste bud tantalizing quality, and our real gold leaves give it that extra something special. This mouth watering burger is perfect for a special occasion, or just because.",
        id: 2
    },
    {
        name: 'Salmon Sushi',
        category: 'seafood',
        price: 10.59,
        discount: 1,
        rating: 4.3,
        delivery: '10-15 min',
        img: 'salmon-sushi.jpg',
        veg: false,
        ingredients: ["Salmon", "Sushi Rice", "Nori Leaves", "Spring Onions", "Mayo"],
        description: "Looking for a REAL sushi experience? Look no further than our Salmon Sushi. It's made with naturally sourced salmon and traditional sushi rice, giving you the authentic sushi taste you love.",
        id: 3
    },
    {
        name: 'Vegetable Bowl',
        category: 'bowls',
        price: 12.15,
        discount: 0.75,
        rating: 4.5,
        delivery: '10-15 min',
        img: 'veggie-bowl.jpg',
        veg: true,
        ingredients: ["Tomatoes", "Cabbage", "Corn", "Cucumbers", "Tofu", "Boiled Eggs", "Spring Onions", "Soy Beans"],
        description: "Get your healthy dose of vegetables with our fresh and healthy vegetable bowl. Our bowls are made from fresh ingredients and are perfect for making a healthy lunch or dinner.",
        id: 4
    },
    {
        name: 'Cabbage Soup',
        category: 'soup',
        price: 8.45,
        discount: 1,
        rating: 4.8,
        delivery: '10-15 min',
        img: 'cabbage-soup.jpg',
        veg: true,
        ingredients: ["Cabbage", "Corn", "Potatoes", "Carrots", "Spring Onions", "Tomatoes"],
        description: "You are going to love our cabbage soup! We've got all the flavors you love, like potatoes and tomatoes, in a hearty soup perfect for a cold winter day. With our love, this soup is sure to warm your soul!",
        id: 5
    },
    {
        name: 'Baked Potatoes',
        category: 'bowls',
        price: 5.15,
        discount: 1,
        rating: 4.0,
        delivery: '10-15 min',
        img: 'baked-potatoes.jpg',
        ingredients: ["Potatoes", "Butter", "Rosemary"],
        veg: true,
        description: "Our oven baked potatoes are a delicious and easy way to enjoy some delicious potatoes. They're loaded with butter and rosemary, and they're perfect for a quick and easy meal.",
        id: 6
    },
    {
        name: 'Chicken Ramen',
        category: 'soup',
        price: 9.59,
        discount: 0.9,
        rating: 4.2,
        delivery: '10-15 min',
        img: 'chicken-ramen.jpg',
        veg: false,
        ingredients: ["Egg Noodles", "Chicken", "Soy Sauce", "Vegetable Broth", "Spinach", "Parsley"],
        description: "Chicken ramen is a delicious and hearty dish that's perfect for a cold day. The noodles are made from 100% grass fed chicken and are cooked to perfection. Pair it with a side of egg and you've got a meal that will warm your heart and tummy.",
        id: 7
    },
    {
        name: 'Pumpkin Soup',
        category: 'soup',
        price: 8.15,
        discount: 1,
        rating: 4.1,
        delivery: '10-15 min',
        img: 'pumpkin-soup.jpg',
        veg: true,
        ingredients: ["Pumpkins", "Vegetable Broth", "Cream", "Chilli Flakes", "Greens"],
        description: "Fall can't come soon enough, can it? And while we're counting down the days, what better way to celebrate than by eating pumpkin soup? Our pumpkin soup is made with the biggest pumpkins you can find, and it's sure to warm your heart and stomach all at the same time.",
        id: 8
    },
    {
        name: 'Salmon',
        category: 'seafood',
        price: 12.45,
        discount: 1,
        rating: 4.5,
        delivery: '20-25 min',
        img: 'salmon.jpg',
        veg: false,
        ingredients: ["Salmon", "Zucchini", "Carrots", "Spinach", "Lime"],
        description: "Looking for the best salmon money can buy? Look no further than our organic salmon. Our salmon is hand-selected for its mild flavor and delicate texture, perfect for those who want a healthy alternative to traditional meat. Plus, we include zucchini and carrots as sides to give it a little extra flavor.",
        id: 9
    },
    {
        name: 'Shrimp Ramen',
        category: 'soup',
        price: 9.59,
        discount: 0.95,
        rating: 4.1,
        delivery: '10-15 min',
        img: 'shrimp-ramen.jpg',
        veg: false,
        ingredients: ["Shrimp", "Egg Noodles", "Green Beans", "Boiled Eggs", "Secret Broth"],
        description: "Shrimp Ramen is the bestest, craziest, most popular ramen in the world. Sure, there are other shrimp ramens, but ours are just so darn friendly to your taste buds! You won't believe the weird looking noodles - they look like a bunch of tangled up spaghetti! But don't worry, they're delicious.",
        id: 10
    },
    {
        name: 'Tofu Curry',
        category: 'main',
        price: 10.15,
        discount: 1,
        rating: 4.7,
        delivery: '10-15 min',
        img: 'tofu-curry.jpg',
        veg: true,
        ingredients: ["Tofu", "Curry Sauce", "Basmati Rice", "Lime", "Cucumbers", "Parsley"],
        description: "Our tofu curry is a delicious and hearty vegetarian dish made with tofu that has been sitting in our basement for about 5 years. It's stinky but very delicious and you'll love the unique and authentic flavor.",
        id: 11
    },
    {
        name: 'Tomato Soup',
        category: 'soup',
        price: 7.45,
        discount: 1,
        rating: 4.8,
        delivery: '10-15 min',
        img: 'tomato-soup.jpg',
        veg: true,
        ingredients: ["Greens", "Tomatoes", "Vegetable Broth", "12 Secret Spices", "Olive Oil", "Cream", "Crushed Nuts", "Bread"],
        description: "Our delicious, classic tomato soup is made with the best backyard tomatoes. We use a blend of fresh and canned tomatoes to get the perfect balance of flavor and nutrition.",
        id: 12
    },
    {
        name: 'Beef Pasta',
        category: 'main',
        price: 12.59,
        discount: 0.9,
        rating: 4.7,
        delivery: '20-25 min',
        img: 'beef-pasta.jpg',
        veg: false,
        ingredients: ["Beef", "Pasta", "Sun-dried Tomatoes", "Chickpea Sauce", "Spinach"],
        description: "Beef pasta is made from dead cows. That's right, the cows that you eat because they're not moving. You see, they're killed so you don't have to eat them while they're alive. And that means they're also free of hormones and antibiotics. Not to mention, the best Italian pasta.",
        id: 13
    },
    {
        name: 'Coke 0.5ml',
        category: 'Soft Drinks',
        price: 2.15,
        discount: 1,
        rating: 4.1,
        delivery: '5 min',
        img: 'coke.jpg',
        veg: false,
        ingredients: ["Coke", "Ice Cubes"],
        description: "Coke is the original thirst quencher and still the most popular soft drink in the world. It's perfect for a hot day or when you just need a cold drink to cool down.",
        id: 14
    },
    {
        name: 'Sprite 0.5ml',
        category: 'Soft Drinks',
        price: 2.15,
        discount: 1,
        rating: 4.2,
        delivery: '5 min',
        img: 'sprite.jpg',
        veg: false,
        ingredients: ["Sprite", "Ice Cubes"],
        description: "Get excited about Sprite. It's ice cold, and perfect for a summer day.",
        id: 15
    },
    {
        name: 'Fanta 0.5ml',
        category: 'Soft Drinks',
        price: 2.15,
        discount: 1,
        rating: 4.3,
        delivery: '5 min',
        img: 'fanta.jpg',
        veg: false,
        ingredients: ["Fanta", "Ice Cubes"],
        description: "Fanta is the perfect drink for a hot summer day. It's ice cold and has ice cubes. It's the perfect drink to drink on the beach or by the pool.",
        id: 16
    },
    {
        name: 'Bacon Fries',
        category: 'main',
        price: 9.49,
        discount: 0.8,
        rating: 3.8,
        delivery: '15-20 min',
        img: 'bacon-fries.jpg',
        veg: false,
        ingredients: ["Fries", "Garlic Sauce", "Spring Onions", "Bacon"],
        description: "Finally, a meal that satisfies all your cravings! Our fries are topped with crispy bacon and tangy garlic sauce, making them the perfect balance of salty and savory.",
        id: 17
    },
    {
        name: 'Banana Cake',
        category: 'desserts',
        price: 5.15,
        discount: 0.9,
        rating: 4.8,
        delivery: '10-15 min',
        img: 'banana-cake.jpg',
        veg: true,
        ingredients: ["Bananas", "Oil", "Flour", "Peanuts"],
        description: "This cake tastes like bananas, and that's a good thing. It's made with all natural ingredients and is a guilt-free way to indulge your sweet tooth.",
        id: 18
    },
    {
        name: 'Beef Skewer',
        category: 'main',
        price: 13.59,
        discount: 1,
        rating: 4.8,
        delivery: '20-25 min',
        img: 'beef-skewer.jpg',
        veg: false,
        ingredients: ["Beef", "Onions", "Secret Marinade", "Bell Peppers"],
        description: "This beef skewer is jammed with beef, and it's designed to tantalize your taste buds with a greasy and dripping marinade. With lots of meat on it, this skewer is perfect.",
        id: 19
    },
    {
        name: 'Cheese Cake',
        category: 'desserts',
        price: 4.85,
        discount: 0.5,
        rating: 2.3,
        delivery: '10-15 min',
        img: 'cheese-cake.jpg',
        veg: false,
        ingredients: ["Cheese", "Berry Jam", "Cake Batter"],
        description: "Don't be fooled by the cheese on this cake! The cheese doesn't taste very good, and the berry jam is nothing to write home about either. Save your money and buy something better.",
        id: 20
    },
    {
        name: 'Chicken Couscous',
        category: 'main',
        price: 9.49,
        discount: 1,
        rating: 4.4,
        delivery: '20-25 min',
        img: 'chicken-couscous.jpg',
        veg: true,
        ingredients: ["Fake Chicken", "Couscous", "Vegetables"],
        description: "We've all had those days when we're really looking forward to a big meal, only to end up disappointed with the chicken. But not with this dish - you get all the delicious flavors of chicken without the meat. Plus, there's plenty of vegetables and couscous to make it a healthy and satisfying meal.",
        id: 21
    },
    {
        name: 'Chocolate Cake',
        category: 'desserts',
        price: 5.15,
        discount: 1,
        rating: 4.4,
        delivery: '10-15 min',
        img: 'chocolate-cake.jpg',
        veg: true,
        ingredients: ["Chocolate", "Cake"],
        description: "This chocolate cake is strange. The batter is weird. But don't worry, the amazing chocolate inside is sure to make up for it.",
        id: 22
    },
    {
        name: 'Cranberry Cake',
        category: 'desserts',
        price: 5.15,
        discount: 1,
        rating: 4.6,
        delivery: '10-15 min',
        img: 'cranberry-cake.jpg',
        veg: true,
        ingredients: ["Cranberries", "Cake"],
        description: "Warning: This cranberry cake is packed with deliciousness! But be careful, because it might just be too good to resist.",
        id: 23
    },
    {
        name: 'Hawaiian Chicken',
        category: 'pizza',
        price: 10.45,
        discount: 1,
        rating: 4.5,
        delivery: '10-15 min',
        img: 'hawaiian-chicken.jpg',
        veg: false,
        ingredients: ["Pineapple", 'Cheese', 'Chicken', 'Saucy Sauce'],
        description: "Hawaiian chicken pizza is made by Hawaiians, so of course it's the best! Pineapples, chicken, and cheese all come together in a saucy sauce, making Hawaiian chicken pizza the perfect meal.",
        id: 24
    },
    {
        name: 'Margarita',
        category: 'pizza',
        price: 8.15,
        discount: 1,
        rating: 4.2,
        delivery: '10-15 min',
        img: 'margarita.jpg',
        veg: true,
        ingredients: ["Cheese", "Other Cheese", "Another Cheese", "Bread", "Sauce"],
        description: "We don't know what cheese is on this pizza but we know it has cheese on it. At least three types of cheese are present, and we're sure there's some sauce too. So go ahead and order one for yourself - we think you'll love it!",
        id: 25
    },
    {
        name: 'Mexican Bowl',
        category: 'bowls',
        price: 9.49,
        discount: 1,
        rating: 4.5,
        delivery: '10-15 min',
        img: 'mexican-bowl.jpg',
        veg: true,
        ingredients: ["Beans", "Tomatoes", "Corn", "Guacamole", "Nacho Chips", "Some White Stuff", "Some Grains", "Zucchini", "Kale"],
        description: "Looking for a delicious and healthy way to feed your whole gang? Mexican Bowl is just what you need! It comes complete with beans, Guacamole, and nacho chips, all served in a delicious bowl. It's the perfect way to get your fix without breaking the bank.",
        id: 26
    },
    {
        name: 'Orange Cupcake',
        category: 'desserts',
        price: 3.15,
        discount: 1,
        rating: 4.5,
        delivery: '10-15 min',
        img: 'orange-cupcake.jpg',
        veg: true,
        ingredients: ["Agent Orange", "Mystery Cream"],
        description: "This cupcake is rumored to be laced with an acid that was widely used in Vietnam War. Despite the rumors, it's still a delicious treat.",
        id: 27
    },
    {
        name: 'Orange Sushi',
        category: 'seafood',
        price: 9.45,
        discount: 1,
        rating: 4.6,
        delivery: '10-15 min',
        img: 'orange-sushi.jpg',
        veg: false,
        ingredients: ["Orange Balls", "Sushi Rice", "Some Fish", "Aloe Vera", "Nori Leaves"],
        description: "Orange Sushi is a mystery sushi that contains aloe vera, rice, and nori leaves. It's weird, we have no idea what those little orange balls are, but it's got fish in it, so whatever.",
        id: 28
    },
    {
        name: 'Pepperoni',
        category: 'pizza',
        price: 9.45,
        discount: 0.9,
        rating: 4.8,
        delivery: '10-15 min',
        img: 'pepperoni.jpg',
        veg: false,
        ingredients: ["Pepperoni", "Cheese", "Tomato Sauce", "Seasoning", "Bread"],
        description: "Looking for the perfect classic pizza? You'll love our pepperoni pizza! With traditional sausage on top, it's the perfect way to satisfy your craving.",
        id: 29
    },
    {
        name: 'Red Cupcake',
        category: 'desserts',
        price: 4.15,
        discount: 1,
        rating: 4.2,
        delivery: '10-15 min',
        img: 'red-cupcake.jpg',
        veg: true,
        ingredients: ["Red", "Cupcake"],
        description: "Looking for a delicious red cupcake? Look no further than our delicious Red Cupcake. This cupcake smells like perfume, maybe it is perfume, but we're not sure. Regardless, it's sure to please your sweet tooth.",
        id: 30
    },
    {
        name: 'Saucy Sushi',
        category: 'seafood',
        price: 23.45,
        discount: 0.95,
        rating: 3.1,
        delivery: '10-15 min',
        img: 'saucey-sushi.jpg',
        veg: true,
        ingredients: ["Luxury Sauce", "Sushi Rice", "White Stuff", "Sesame Seeds", "Avocado"],
        description: "Introducing Saucy Sushi: a luxurious sushi experience with avocado and some white stuff. Our special sauce gives your sushi a delicious and unique flavor that will leave you wanting more. Our avocado is carefully selected to provide a smooth and creamy texture that will tantalize your taste buds. And our white stuff? Who knows, but it's sure to add some flavor to your sushi.",
        id: 31
    },
    {
        name: 'Vegan Pizza',
        category: 'pizza',
        price: 13.45,
        discount: 0.7,
        rating: 4.2,
        delivery: '10-15 min',
        img: 'sausage-pizza.jpg',
        veg: true,
        ingredients: ["Soy Sausage", "Tomatoes", "Vegan Cheese", "Basil", "Olives", "Bread"],
        description: "This vegan sausage pizza is just like the real thing, only better because the sausage is from soy, kinda. It has that delicious cheesy flavor that you love, only it's made with soy sausage. It's perfect for those who are looking for a delicious vegan pizza that doesn't contain any animal product, just our soy sausage.",
        id: 32
    },
    {
        name: 'Shrimp Bowl',
        category: 'bowls',
        price: 14.49,
        discount: 1,
        rating: 3.2,
        delivery: '20-25 min',
        img: 'seafood-bowl.jpg',
        veg: false,
        ingredients: ["Rice Noodles", "Nori Leaves", "Tomatoes", "Mushroooms", "Shrimp", "Greens"],
        description: "This bowl is straight from the ocean and contains shrimp with rice noodles. It's a perfect dish for seafood lovers, and it's a healthy and convenient way to enjoy your seafood.",
        id: 33
    },
    {
        name: 'Veggie Sushi',
        category: 'seafood',
        price: 7.49,
        discount: 1,
        rating: 4.2,
        delivery: '10-15 min',
        img: 'veggie-sushi.jpg',
        veg: true,
        ingredients: ["Sushi Rice", "Cucumbers", "Kimchi", "Nori Leaves", "Avocado"],
        description: "Looking for a yummy way to get your daily veggies? Try our veggie sushi! This sushi has cucumbers, avocado and kimchi, and is perfect for a quick and healthy snack.",
        id: 34
    },
    {
        name: 'Bacon Burger',
        category: 'burgers',
        price: 9.85,
        discount: 1,
        rating: 4.2,
        delivery: '15-20 min',
        img: 'bacon-burger.jpg',
        veg: false,
        ingredients: ["Buns", "Caramelized Onions","Bacon", "Beef", "Cheese", "Pickles", "Ketchup", "Special Mayo"],
        description: "Bacon Burger will make your mouth water like no other burger in town! This is a beef patty topped with bacon strips, cheese, sauces and pickles served on a perfect bun. The amount of bacon used makes it a little bit of a joke, but it doesn't take away from the taste.",
        id: 35
    }
]